GET http://localhost:3030
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5MTU0NDEsImV4cCI6MTYwODkxNTQ2MSwiYXVkIjoiNWZlNTZiNmQzZWEwOWU0NGJjODJjZmI0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.PNuscZ5kbRceHQANlfXqI3zhEndxVnIgRBNIzEkdwW8

####Login
POST http://localhost:3030/auth/login
Content-Type: application/json

{
    "email": "someemail3e@gmail.com",
    "password": "12345678"
}

####register
POST http://localhost:3030/auth/register
Content-Type: application/json

{
    "email": "someemail3new@gmail.com",
    "password": "12345678"
}

####refresh
POST http://localhost:3030/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5MTUzNTAsImV4cCI6MTY0MDQ3Mjk1MCwiYXVkIjoiNWZlNTZiNmQzZWEwOWU0NGJjODJjZmI0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.baD7UZxe3mvup74Ezo7xgobHw9-vksIsCj7tOj-J3RI"
}


####logout
DELETE http://localhost:3030/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5MTUzNTAsImV4cCI6MTY0MDQ3Mjk1MCwiYXVkIjoiNWZlNTZiNmQzZWEwOWU0NGJjODJjZmI0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.baD7UZxe3mvup74Ezo7xgobHw9-vksIsCj7tOj-J3RI"
}