GET http://localhost:3030

####Login
POST http://localhost:3030/auth/login

####register
POST http://localhost:3030/auth/register
Content-Type: application/json

{
    "email": "someemail@gmail.com",
    "password": "1234"
}

####refresh
POST http://localhost:3030/auth/refresh-token

####logout
DELETE http://localhost:3030/auth/logout